### ISSUE TITLE
URL for downloading egg files incorrect

### ISSUE THREAD

**Issue by nickpowpow** [datacenter/cobra#104]
I'm on version 1.1o and the egg download files are:
https://<APIC address>/cobra/_downloads/acicobra-1.0_3i-py2.7.egg
https://<APIC address>/cobra/_downloads/acimodel-1.0_3i-py2.7.egg

The docs say:
You can download the two .egg files from a running instance of APIC at these URLs:

```
http[s]://<APIC address>/cobra/_downloads/acicobrasdk.egg
http[s]://<APIC address>/cobra/_downloads/acicobramodel.egg
```

**Comment by mtimm** [comment]
Addressed by #109
