### ISSUE TITLE
Minor typo in README

### ISSUE THREAD

**Issue by NathanDotTo** [datacenter/cobra#124]
"We have started documenting the library at http://cobra.readthedocs.org and we would of course greatly appreciate pull requests to help _imporve_ the documentation."

Should be "improve".

Regards

Nathan

**Comment by dagwieers** [comment]
I noticed the same thing just yet and made the PR before I saw this issue.

PS Did you know you can edit files yourself through the Github web interface ? It will automatically create the commit and pull-request without having to know Git commands.

**Comment by NathanDotTo** [comment]
Thanks. I should have fixed that myself then :-/
