### ISSUE TITLE
Enhancement: MIM introspection for MOs

### ISSUE THREAD

**Issue by mrogaski** [datacenter/cobra#127]
There doesn't appear to be a satisfactory way to map an MO returned by a query to the Management Information Model (MIM) class it represents, or to determine the inheritance relationship between two MOs returned by a query for a common ancestor.

For example, if we issue a query for the abstract class `ethpmIf`, we get a list of `ethpmPhysIf` and `ethpmAggrIf` instances.  Because the MO classes are subclassed directly from `cobra.mit.mo.Mo`, normal introspection doesn't reflect MIM inheritance. 

This presents a problem, because we can only tell which model an MO is an instance of if we limit the query to a single, concrete class or if we try to infer the class from the DN. This forces sessions to be extremely chatty and prone to errors.

It would be _extremely_ useful to have the following sort of tests.

``` python
mo.mimClass() == 'ethpmPhysIf'
mo.mimInstanceOf('ethpmIf') == True
mo.mimInstanceOf('ethpmPhysIf') == True
mo.mimInstanceOf('ethpmAggrIf') == False
```

**Comment by giovannimeo** [comment]
Hi Mark,

the first info you are asking:

mo.mimClass is already available as:

mo.meta.moClassName

the other info can be calculated via:

mo.meta.superClasses
and
mo.meta.concreteSubClasses

you can look at the code in:

https://github.com/datacenter/cobra/blob/master/cobra/mit/meta.py

Please let me know if what already existing would be sufficient for you.

Thanks,
Giovanni

**Comment by mrogaski** [comment]
Perfect!  I had missed the moClassName method.  These are exactly what I needed.

Thank you.

**Comment by giovannimeo** [comment]
Very good, glad it helped.

Thanks,
Giovanni
