### ISSUE TITLE
Need to cache minions on shippable

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#33]
Need to setup shippable so that it caches dependancies between builds.  That way builds and tests will be faster.

**Comment by capereir** [comment]
Would that help ?  hub.docker.com/u/dockercisco/aci/

**Comment by mtimm** [comment]
Not really.  We don't need acitoolkit or a webpage.  Shippable is our CI of choice at this point and it natively supports caching of dependencies if you enable the feature.  I enabled the feature in the pull request and tested and it works most of the time.  Shippable currently does not have a centralized cache so if the dependencies change it may take a run or two of tests before it starts to use the cache for all subsequent runs.  Thanks for the suggestion though, I was not aware of this effort.
