### ISSUE TITLE
fix configRequest to support distributed transactions (introduce bundling of requests, based on dn)

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#57]
Question:

What should happen if a distributed commit fails?
  Do we leave it up to the application/user to define?
  Do we back out all previous commits? (ACID model)
  Do we continue forward with the remaining commits?
  Etc.

Simply stating we need to add support is not sufficient.  We need to layout what that means and how it will work.

Response:

We don't do anything. We bundle up the requests into separate configRequest objects. and its up to the user to decide how to proceed. e.g.,: 
crh= configRequestHelper()
crh.addMo(context1)
crh.addMo(context2)
for cr in crh.getDistributedRequests():
  md.commit(cr)

If someone wants to wrap md.commit in a try block, and continue gracefully, they can do that. If someone wants to go and revert roll back logic, they can do that. This is what we had agreed upon

**Comment by paullesiak** [comment]
+1

**Comment by mtimm** [comment]
After discussing this with Ravi, the biggest issue here is failure scenarios.  How do you inform the user which transaction failed?  Do you rollback the transactions that were previously successful?  

Ravi basically said if an application wants to do this, they can but then it is up to the application to define the behavior.  He would prefer that we don't add something to the SDK for this until something is provided on the backend at which point it is assumed that the backend would handle all requests and this becomes a non-issue for the most part.

For this reason this issue is being closed but can certainly be reopened if the backend changes or some better way is identified that doesn't introduce very complex logic into the SDK.

**Comment by paullesiak** [comment]
"After discussing this with Ravi, the biggest issue here is failure scenarios. How do you inform the user which transaction failed? Do you rollback the transactions that were previously successful?"

The goal behind the helper shouldn't be to ensure atomic commits, but rather do the chunking for the user. The helper should not commit anything, but rather break up a ConfigRequest into multiple smaller ConfigRequests, if the contextRoot for the Mo's differ in the original ConfigRequest. If one of those broken up ConfigRequests fails, the responsibility should be left to the user. 

Fine with not adding this to the SDK, but I'll be creating a gist for this to at least give people an idea of how to work around it.

**Comment by mtimm** [comment]
That's fair and what I think should happen.  The decision is to not include it in the SDK as a "solution" I think it could be included as an example.

**Comment by rchamarthy** [comment]
I am fine with adding it as an example to begin with and based on the traction we see in terms of reuse, we can promote it into the API.
