### ISSUE TITLE
Pylint or some other linter should be run and tied into shippable if possible

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#65]
I ran pylint against the entire cobra code base and with the default settings the code quality is pretty horrible.  However, I think we can bring that up significantly if we use a pylintrc file and loosen up things a bit then clean out some of the issues pylint finds.

**Comment by rchamarthy** [comment]
We should do this as soon as possible. Can you setup the preliminary configuration required?

**Comment by mtimm** [comment]
Already started

**Comment by mtimm** [comment]
I'm thinking we should look into https://coveralls.io/ and https://landscape.io/ for some of this.  I wish we didn't have to have 2 or 3 different services to do CI, coverage (in a nice way, shippable can do it but the visualization features seem lacking) and pylint.

**Comment by mtimm** [comment]
Example output of landscape.io:  https://landscape.io/github/datacenter/cobra/7/modules

**Comment by rchamarthy** [comment]
Looks good but is this another thing we need to wait for before merge. In any case i want the code to get into shape. Lets formalize this.

**Comment by mtimm** [comment]
I agree, it is a thing to wait for.  However, it only takes about 20 seconds once a commit is pushed or a pull request is submitted.
