### ISSUE TITLE
Add support for aaaListDomains query prior to login

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#7]
aaaListDomains provides a list of domains, the APIC banner, etc.  Once a MoDirectory is setup with a session it should be possible to have a method that does the aaaListDomains query if the user needs them.  The domains list can then be used to login to various aaa Domains.  

This query will need to be called without a userid so the LoginSession class may need to be changed to allow it to be instantiated without a user or maybe update the user.

**Comment by rchamarthy** [comment]
Is this even possible today with the REST API?

**Comment by mtimm** [comment]
Yes:  http://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/1-x/api/rest/b_APIC_RESTful_API_User_Guide/b_IFC_RESTful_API_User_Guide_chapter_010.html#concept_D16AC6DC9CCD4351A4A40287487F061A

**Comment by mtimm** [comment]
I'd prefer to not see movement on this one until #44 is taken care of.  Any work on this will likely have to be redone once those changes are made.

**Comment by mtimm** [comment]
Closed by #74
