### ISSUE TITLE
Using removeMo()

### ISSUE THREAD

**Issue by jedelman8** [datacenter/cobra#97]
Hi,

I'm trying to remove a tenant using Cobra and want to verify proper usage.  Can someone please advise?

Below is the code and error I'm getting:

```
>>> fvTenantMo = Tenant(uniMo, 'JASON_EDELMAN_TENANT')
>>> 
>>> tenantCfg = ConfigRequest()
>>> 
>>> tenantCfg.removeMo(fvTenantMo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.0_3f-py2.7.egg/cobra/mit/request.py", line 614, in removeMo
    del self.__configMos[mo.dn]
KeyError: <cobra.mit.naming.Dn object at 0x7f8ec9c18850>
```

Testing is being done on dCloud with the 1.0_3f egg files.

Thanks,
Jason

**Comment by mcknucs1** [comment]
Hi Jason,

Thank you for the question.

`removeMo()` is used to remove a managed object from a `ConfigRequest` that has already been added.  Here you are removing a Mo that has never been added.

If you would like to delete a tenant, you should mark the tenant as deleted then commit that tenant to the APIC:

```
fvTenantMo = Tenant(uniMo, 'JASON_EDELMAN_TENANT')
fvTenantMo.delete()
tenantCfg = ConfigRequest()
tenantCfg.addMo(fvTenantMo)
moDir.commit(tenantCfg)
```

Hope that helps,

Mike

**Comment by jedelman8** [comment]
Perfect.  Thank you.  BTW, you have a typo in your last line! :)

And is this documented anywhere?  All examples I can see show how to
configure objects, but not remove them.

Thanks,
Jason

**Comment by paullesiak** [comment]
It's documented here:

http://cobra.readthedocs.org/en/latest/api-ref/request.html#cobra.mit.request.ConfigRequest.removeMo

**Comment by mtimm** [comment]
Closing as I think this question was answered, feel free to reopen if there are still questions.
